"""P6: whatsapp message log

Revision ID: 8adf848519da
Revises: 30b9b373298c
Create Date: 2026-08-08 01:16:49.911252

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8adf848519da'
down_revision = '30b9b373298c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('to_phone', sa.String(length=24), nullable=False),
    sa.Column('from_phone', sa.String(length=24), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='messagestatus', native_enum=False, length=12), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('batch_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'batch_date', name='uq_whatsapp_daily_once')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_batch_date'), ['batch_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_student_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_status'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_batch_date'))

    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
