"""Add expenses table for budget module

Revision ID: b23d7d509af2
Revises: c1e0f2a7b93d
Create Date: 2026-08-15 15:35:10.229511

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b23d7d509af2'
down_revision = 'c1e0f2a7b93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('rent', 'assistant_salary', 'electricity', 'internet', 'water', 'gas', 'partner_share', 'other', name='expensecategory', native_enum=False, length=24), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('amount_egp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_month'), ['month'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_month'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    # ### end Alembic commands ###
