"""P2: course types, courses, slots, enrollments

Revision ID: b68e62ee86c8
Revises: fde2c6588ffc
Create Date: 2026-08-07 20:11:02.062942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68e62ee86c8'
down_revision = 'fde2c6588ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_types',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ar', sa.String(length=120), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Enum('month', 'round', name='coursecycle', native_enum=False, length=10), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('has_own_subject', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('course_type_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_path', sa.String(length=255), nullable=True),
    sa.Column('price_egp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trial_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='coursestatus', native_enum=False, length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_type_id'], ['course_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_course_type_id'), ['course_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('course_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_course_slots_duration'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_course_slots_weekday'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_slots_course_id'), ['course_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('booking_status', sa.Enum('trial', 'booked', 'not_booked', name='bookingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'unpaid', name='paymentstatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_enrollment_once')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('course_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_slots_course_id'))

    op.drop_table('course_slots')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_course_type_id'))

    op.drop_table('courses')
    op.drop_table('course_types')
    # ### end Alembic commands ###
