"""P3: sessions and attendance records

Revision ID: fa1c9f064b95
Revises: b68e62ee86c8
Create Date: 2026-08-07 21:28:27.737884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1c9f064b95'
down_revision = 'b68e62ee86c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'held', 'cancelled_by_teacher', 'cancelled_by_center', 'rescheduled', name='sessionstatus', native_enum=False, length=24), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_status', sa.Enum('present', 'absent', 'late', 'excused', name='attendancestatus', native_enum=False, length=12), nullable=True),
    sa.Column('teacher_checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['course_slots.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sequence_no', name='uq_session_sequence')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'excused', name='attendancestatus', native_enum=False, length=12), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_once')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_session_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_sessions_course_id'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
