"""P1: users, profiles, parent links, terms, audit log

Revision ID: fde2c6588ffc
Revises: 
Create Date: 2026-08-06 01:18:59.952461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde2c6588ffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.Enum('teacher', 'student_parent', name='termsaudience', native_enum=False, length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_ar', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience', 'version', name='uq_terms_versions_audience_version')
    )
    with op.batch_alter_table('terms_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_versions_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_versions_is_current'), ['is_current'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'assistant', 'teacher', 'student', 'parent', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(username IS NULL) OR (password_hash IS NOT NULL)', name='ck_users_login_needs_password'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('parent_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=True),
    sa.CheckConstraint('parent_id != student_id', name='ck_parent_links_distinct'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_links_pair')
    )
    with op.batch_alter_table('parent_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_links_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_links_student_id'), ['student_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=120), nullable=True),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('payout_share', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('terms_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_version_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['terms_version_id'], ['terms_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'terms_version_id', name='uq_terms_acceptance_once')
    )
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_acceptances_terms_version_id'), ['terms_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_acceptances_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_acceptances_user_id'))
        batch_op.drop_index(batch_op.f('ix_terms_acceptances_terms_version_id'))

    op.drop_table('terms_acceptances')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    with op.batch_alter_table('parent_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_links_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_links_parent_id'))

    op.drop_table('parent_links')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('terms_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_versions_is_current'))
        batch_op.drop_index(batch_op.f('ix_terms_versions_audience'))

    op.drop_table('terms_versions')
    # ### end Alembic commands ###
